add_executable(basic_order basic_order.cpp)
target_link_libraries(basic_order PRIVATE hyperliquid)

add_executable(market_data_websocket market_data_websocket.cpp)
target_link_libraries(market_data_websocket PRIVATE hyperliquid)

add_executable(market_data_websocket_user_thread_dispatch market_data_websocket_user_thread_dispatch.cpp)
target_link_libraries(market_data_websocket_user_thread_dispatch PRIVATE hyperliquid)

add_executable(market_data_websocket_per_coin market_data_websocket_per_coin.cpp)
target_link_libraries(market_data_websocket_per_coin PRIVATE hyperliquid)

add_executable(market_data_websocket_per_coin_user_thread_dispatch market_data_websocket_per_coin_user_thread_dispatch.cpp)
target_link_libraries(market_data_websocket_per_coin_user_thread_dispatch PRIVATE hyperliquid)

add_executable(market_data_websocket_shm_reader market_data_websocket_shm_reader.cpp)
target_link_libraries(market_data_websocket_shm_reader PRIVATE hyperliquid slick::stream_buffer_multiplexer)
